### PR TITLE
Fix Microchip MCP3008 sample interactive test documentation

### LINKED ISSUE #306: Fix Microchip MCP3008 sample interactive test documentation
Fix Microchip MCP3008 sample interactive test documentation:
- [x] description for `main()` is not correct

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #306 (Fix Microchip MCP3008 sample interactive test
documentation).

This pull request:
- [x] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [ ] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: test/interactive/picolibrary/microchip/mcp3008/sample/main.cc [hunk 1]
```diff
@@ -58,8 +58,7 @@ using Controller = ::picolibrary::Microchip::megaAVR::SPI::Controller<SPI>;
 } // namespace
 
 /**
- * \brief Execute the
- *        picolibrary::Microchip::megaAVR::SPI::Controller<picolibrary::Microchip::megaAVR::Peripheral::SPI>
+ * \brief Execute the picolibrary::Microchip::MCP3008 sample interactive test.
  *        echo interactive test.
```
Comment (apcountryman) [inline test/interactive/picolibrary/microchip/mcp3008/sample/main.cc:62]:
```suggestion
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
