### PR TITLE
Add Microchip megaAVR SPI based fixed configuration SPI basic controller

### LINKED ISSUE #545: Add Microchip megaAVR SPI based fixed configuration SPI basic controller
Add Microchip megaAVR SPI based fixed configuration SPI basic controller (`::picolibrary::Microchip::megaAVR::SPI::Fixed_Configuration_Basic_Controller<Peripheral::SPI>`).
- [x] The `Fixed_Configuration_Basic_Controller<Peripheral::SPI>` template class specialization should be defined in the `include/picolibrary/microchip/megaavr/spi.h`/`source/picolibrary/microchip/megaavr/spi.cc` header/source file pair
- [x] The `Fixed_Configuration_Basic_Controller<Peripheral::SPI>` template class specialization should have the following member types:
    - [x] `struct Configuration {};`: Clock (frequency, polarity, and phase) and data exchange bit order configuration
- [x] The `Fixed_Configuration_Basic_Controller<Peripheral::SPI>` template class specialization should support the following operations:
    - [x] `constexpr Fixed_Configuration_Basic_Controller() noexcept = default;`
    - [x] `Fixed_Configuration_Basic_Controller( Peripheral::SPI & spi, SPI_Clock_Rate spi_clock_rate, SPI_Clock_Polarity spi_clock_polarity, SPI_Clock_Phase spi_clock_phase, SPI_Bit_Order spi_bit_order ) noexcept;`
    - [x] `constexpr Fixed_Configuration_Basic_Controller( Fixed_Configuration_Basic_Controller && source ) noexcept;`
    - [x] `~Fixed_Configuration_Basic_Controller() noexcept;`
    - [x] `constexpr auto operator=( Fixed_Configuration_Basic_Controller && expression ) noexcept -> Fixed_Configuration_Basic_Controller &;`
    - [x] `void initialize() noexcept;`: Initialize the controller's hardware
    - [x] `void configure( Configuration configuration ) noexcept;`: Configure the controller's clock and data exchange bit order to meet a specific device's communication requirements
    - [x] `auto exchange( std::uint8_t data ) noexcept -> std::uint8_t;`: Exchange data with a device

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #545 (Add Microchip megaAVR SPI based fixed configuration SPI
basic controller).

This pull request:
- [ ] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [x] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: include/picolibrary/microchip/megaavr/spi.h [hunk 1]
```diff
@@ -126,6 +129,222 @@ template<typename Peripheral>
...
+     */
+    void enable_controller() noexcept
+    {
+        m_spi->spcr |= Peripheral::SPI::SPCR::Mask::SPE;
+    }
+
+    /**
+     * \brief Initiate a data exchange.
+     *
+     * \param[in] data The data transmit.
```
Comment (apcountryman) [inline include/picolibrary/microchip/megaavr/spi.h:319]:
```suggestion
     * \param[in] data The data to transmit.
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
