### PR TITLE
Add Microchip megaAVR USART based fixed configuration SPI basic controller

### LINKED ISSUE #548: Add Microchip megaAVR USART based fixed configuration SPI basic controller
Add Microchip megaAVR USART based fixed configuration SPI basic controller (`::picolibrary::Microchip::megaAVR::SPI::Fixed_Configuration_Basic_Controller<Peripheral::USART>`).
- [x] The `Fixed_Configuration_Basic_Controller<Peripheral::USART>` template class specialization should be defined in the `include/picolibrary/microchip/megaavr/spi.h`/`source/picolibrary/microchip/megaavr/spi.cc` header/source file pair
- [x] The `Fixed_Configuration_Basic_Controller<Peripheral::USART>` template class specialization should have the following member types:
    - [x] `struct Configuration {};`: Clock (frequency, polarity, and phase) and data exchange bit order configuration
- [x] The `Fixed_Configuration_Basic_Controller<Peripheral::USART>` template class specialization should support the following operations:
    - [x] `constexpr Fixed_Configuration_Basic_Controller() noexcept = default;`
    - [x] `Fixed_Configuration_Basic_Controller( Peripheral::USART & usart, std::uint16_t usart_clock_generator_scaling_factor, USART_Clock_Polarity usart_clock_polarity, USART_Clock_Phase usart_clock_phase, USART_Bit_Order usart_bit_order ) noexcept;`
    - [x] `constexpr Fixed_Configuration_Basic_Controller( Fixed_Configuration_Basic_Controller && source ) noexcept;`
    - [x] `~Fixed_Configuration_Basic_Controller() noexcept;`
    - [x] `constexpr auto operator=( Fixed_Configuration_Basic_Controller && expression ) noexcept -> Fixed_Configuration_Basic_Controller &;`
    - [x] `void initialize() noexcept;`: Initialize the controller's hardware
    - [x] `void configure( Configuration configuration ) noexcept;`: Configure the controller's clock and data exchange bit order to meet a specific device's communication requirements
    - [x] `auto exchange( std::uint8_t data ) noexcept -> std::uint8_t;`: Exchange data with a device

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #548 (Add Microchip megaAVR USART based fixed configuration SPI
basic controller).

Resolves #.

This pull request:
- [ ] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [x] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: include/picolibrary/microchip/megaavr/spi.h [hunk 1]
```diff
@@ -345,6 +345,265 @@ class Fixed_Configuration_Basic_Controller<Peripheral::SPI> {
...
+     */
+    void disable_controller() noexcept
+    {
+        m_usart->spi_host.ucsrb = 0;
+    }
+
+    /**
+     * \brief Clear the USART's clock generator scaling factor (UBRR register value).
+     *
+     * \return The previous USART clock generator scaling factor.
```
Comment (apcountryman) [inline include/picolibrary/microchip/megaavr/spi.h:533]:
```suggestion
     * \return The previous USART clock generator scaling factor (UBRR register value).
```
